### ISSUE TITLE
Can't import base linode.box

### ISSUE THREAD

**Issue by joaco1977** [displague/vagrant-linode#55]
I don't know if it's really an issue, but when a try to import the linode.box, getting this error:

"The metadata associated with the box 'linode' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again"

I've tried in more than one machine
If I can help please let me know

**Comment by displague** [comment]
I believe this has been corrected in v0.2.4.

**Comment by displague** [comment]
@joaco1977 Has the problem been resolved?

**Comment by CTIGB** [comment]
I'm getting the same issue mentioned above using the latest version just installed today

**Comment by CTIGB** [comment]
Grahams-Mac-Pro:linode grahambrown$ vagrant box add dummy https://github.com/displague/vagrant-linode/raw/master/box/linode.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'dummy' (v0) for provider: 
    box: Downloading: https://github.com/displague/vagrant-linode/raw/master/box/linode.box
The metadata associated with the box 'dummy' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.

**Comment by kmgalanakis** [comment]
Having the same issue as above. Anyone solved this?

**Comment by displague** [comment]
This has been fixed - there was javascript instead of json in metadata.json 

```
vagrant box add dummy https://github.com/displague/vagrant-linode/raw/master/box/linode.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'dummy' (v0) for provider:
    box: Downloading: https://github.com/displague/vagrant-linode/raw/master/box/linode.box
==> box: Successfully added box 'dummy' (v0) for 'linode'!
```
