### ISSUE TITLE
is there a way to vagrant destroy but not remove (but rebuild) linode?

### ISSUE THREAD

**Issue by elimau** [displague/vagrant-linode#75]
Hi,
With Linode CLI, we have `linode delete`. That seems to be equivalent to `vagrant destroy`.  The linode instance is completely `removed`.

However the Linode CLI also has `linode rebuild` which can be used to keep that same linode but we do a full image installation from scrach. Is there a way to do this with vagrant?
Thanks very much.

**Comment by displague** [comment]
The rebuild command should do what you want.  This was merged in https://github.com/displague/vagrant-linode/pull/67.

I should probably close https://github.com/displague/vagrant-linode/issues/42.

Add another Linode and use it on that one to make sure it works the way you would expect.  Rebuild is a dangerous feature.

**Comment by displague** [comment]
The `vagrant rebuild some_linode_name` command will reapply your Vagrantfile settings over the Linode that was previously configured at `some_linode_name`.  This will issue a Linode Rebuild command, preserving the IP address and history of the Linode.

This feature hasn't received much scrutiny, and is otherwise pretty scary, so proceed with caution.

If you attempted to use it before and it didn't seem to do anything, this command requires the Linode to be powered off.  Up until version 0.3.0 of this plugin, it didn't report that reason before giving up.
